version: "3.9"

services:
  django:
    container_name: api
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    depends_on:
      - psql

  react:
    container_name: app
    build:
      context: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src

  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: