# Generated by Django 4.0.4 on 2022-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('B', 'Borrow'), ('S', 'Sell')], default='S', max_length=1)),
            ],
        ),
    ]
