# Generated by Django 4.0.4 on 2022-12-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brick.user'),
        ),
    ]
