# Generated by Django 4.0.4 on 2022-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0004_tag_rename_user_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
