# Generated by Django 4.0.4 on 2022-12-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0005_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('B', 'Borrow'), ('S', 'Sell'), ('C', 'Colab')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
