# Generated by Django 4.0.4 on 2022-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brick', '0006_remove_post_tags_alter_post_type_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('B', 'Borrow'), ('S', 'Sell'), ('C', 'Collab')], default='S', max_length=1),
        ),
    ]
