# Generated by Django 4.1.5 on 2023-01-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('نو', 'نو'), ('در حد نو', 'در حد نو'), ('کارکرده', 'کارکرده')], default='کارکرده', max_length=20),
        ),
    ]
