# Generated by Django 4.1.5 on 2023-01-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_contact_type_alter_post_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('فروش رفته', 'فروش رفته'), ('در دسترس', 'در دسترس')], default='در دسترس', max_length=20),
        ),
    ]
