# Generated by Django 4.1.5 on 2023-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('فروش رفته', 'فروش رفته'), ('در دسترس', 'در دسترس')], default='فروش رفته', max_length=20),
        ),
    ]
