# Generated by Django 4.1.5 on 2023-01-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
